#!/usr/bin/env bats
#
# The Composer autoloader mu-plugin (#12).

load 'helpers'

setup() {
  setup_project
  MU="${PROJ}/web/wp-content/mu-plugins/000-autoloader.php"
}

@test "a user-owned file at the autoloader path is left untouched and not gitignored" {
  mkdir -p "$(dirname "$MU")"
  printf '<?php // my own bootstrap\n' > "$MU"

  run install_core
  [ "$status" -eq 0 ]

  [ "$(cat "$MU")" = "<?php // my own bootstrap" ]
  [[ "$output" == *"was not generated by this plugin"* ]] || false
  ! grep -q '000-autoloader.php' "${PROJ}/.gitignore" || false
}

@test "a file generated by 1.1.x (no @generated marker) is still refreshed" {
  mkdir -p "$(dirname "$MU")"
  printf '<?php\n/*\n * Author:       kanopi/wp-core-installer\n */\n// stale\n' > "$MU"

  run install_core
  [ "$status" -eq 0 ]

  grep -q '@generated kanopi/wp-core-installer' "$MU"
  ! grep -q '// stale' "$MU" || false
}

@test "no mu-plugin is written when no wordpress-core package is installed" {
  run composer_in_project require "kanopi/wp-core-installer:*"
  [ "$status" -eq 0 ]

  [ ! -e "$MU" ]
  ! grep -q '000-autoloader.php' "${PROJ}/.gitignore" || false
}
